### ISSUE TITLE
Not working without Internet connexion available

### ISSUE THREAD

**Issue by Phil353556** [swiftyapp/swifty#100]
Hi, I consider this is a bug.  
As it MUST be possible to use a password manager localy without any Internet connexion available.

$ ./Swifty-0.6.5.AppImage 
13:29:59.661 › Checking for update
13:30:00.600 › Error: Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

Swifty-0.6.5.AppImage  was downloaded from https://getswifty.pro/
then chmod 700 ./Swifty-0.6.5.AppImage
then run it ./Swifty-0.6.5.AppImage
with an Internet a new version 0.6.6 is detected. 
Why on the website https://getswifty.pro/    this is not the latest version available??

Running on 
- Thinkpad T470
- Ubuntu 20.04.4 LTS 

Thank you for your help

**Comment by Phil353556** [comment]
Hi, 
I checked with the latest version. It works without network connection.
Still have an error message .. 
but not a problem at all.  It works.
![ksnip_20221031-124215](https://user-images.githubusercontent.com/64729485/199000573-9d8b8ea8-2eda-4f26-b223-cbfeefbd9e9c.png)

**Comment by alchaplinsky** [comment]
@Phil353556 Hey does this error pop up on application start?

**Comment by Phil353556** [comment]
Hey Alex
Thanks for your time
yes this pop up comes when the application starts when there is no network


Le lun. 31 oct. 2022 à 12:58, Alex Chaplinsky ***@***.***> a
écrit :

**Comment by alchaplinsky** [comment]
Hey @Phil353556, in v0.6.10 this issue should be resolved. Could you please check to confirm?

**Comment by Phil353556** [comment]
Hi @alchaplinsky,
Please hereunder the trace using first Swifty-0.6.9.AppImage which will download the latest version, and second the run of Swifty-0.6.10.AppImage  with and without network.
Ask me if you need more tests. I will be happy to help you.
platform is: Lenovo Thinkpad T470 under ubuntu 22.04 LTS.
Phil

```
$ ./Swifty-0.6.9.AppImage
10:21:45.855 › Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[46342:1108/102150.578744:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
10:21:52.734 › Found version 0.6.10 (url: Swifty-0.6.10.AppImage)
10:21:52.735 › Downloading update from Swifty-0.6.10.AppImage
10:21:52.736 › updater cache dir: /home/xxxxxx/.cache/swifty-updater
10:21:52.742 › Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: Fikk5jLhgpWW1mgnwPqzeR/cMFbvCFnMPQVJh7ScecK7HrNACImpCRQ53R35NhxS+oX3PrPoif9Q49KQWoo6nA==, expected: VzuxUwhXTPIApfpQpDpMsk74FvkungFlntS8C8YVVRq63rP5cNIXmUYPb7aI9nJ2FCNO/nBKTfX72Biff4e/xA==. Directory for cached update will be cleaned
[46342:1108/102153.362453:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
10:21:56.225 › File has 47 changed blocks
10:21:56.225 › [
  {
    "kind": 0,
    "start": 0,
    "end": 159006
  },
  {
    "kind": 1,
    "start": 159006,
    "end": 191774
  },
  {
    "kind": 0,
    "start": 191774,
    "end": 20744917
  },
  {
    "kind": 1,
    "start": 20744917,
    "end": 20938058
  },
  {
    "kind": 0,
    "start": 20938058,
    "end": 20950477
  },
  {
    "kind": 1,
    "start": 20950477,
    "end": 21718222
  },
  {
    "kind": 0,
    "start": 21718237,
    "end": 92585413
  },
  {
    "kind": 1,
    "start": 92585398,
    "end": 92616515
  },
  {
    "kind": 0,
    "start": 92616530,
    "end": 92996698
  },
  {
    "kind": 1,
    "start": 92996683,
    "end": 93036520
  }
]
10:21:56.266 › Full: 90,952.32 KB, To download: 1,039.66 KB (1%)
10:21:56.268 › Differential download: https://github.com/alchaplinsky/swifty/releases/download/v0.6.10/Swifty-0.6.10.AppImage
10:21:56.271 › download range: bytes=159006-191773
10:21:56.293 › Redirect to https://github.com/swiftyapp/swifty/releases/download/v0.6.10/Swifty-0.6.10.AppImage
10:21:56.316 › Redirect to https://objects.githubusercontent.com/github-production-release-asset-2e65be/194523292/43fef7da-cb97-4ade-8c88-c5c39fb6ecdd
10:21:56.569 › download range: bytes=20744917-20938057
10:21:56.679 › download range: bytes=20950477-21718221
10:21:57.320 › download range: bytes=92585398-92616514
10:21:57.437 › download range: bytes=92996683-93036519
10:21:57.545 › New version 0.6.10 has been downloaded to /home/xxxxx/.cache/swifty-updater/pending/Swifty-0.6.10.AppImage
10:22:14.462 › Google oAuth is configured
10:22:14.468 › Google oAuth is configured
[46342:1108/102217.101104:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

10:22:24.208 › Auto install update on quit
10:22:24.210 › Install: isSilent: true, isForceRunAfter: false
```
```

$ ./Swifty-0.6.10.AppImage 
10:22:39.513 › Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
10:22:43.925 › Update for version 0.6.10 is not available (latest version: 0.6.10, downgrade is disallowed).
10:22:43.927 › checkForUpdatesAndNotify called, downloadPromise is null
[46501:1108/102244.244734:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[46501:1108/102249.554398:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[46501:1108/102249.560133:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
10:22:57.374 › Google oAuth is configured
10:22:57.376 › Google oAuth is configured
```
```
$ ./Swifty-0.6.10.AppImage 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[47221:1108/102952.533346:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
10:29:58.059 › Google oAuth is configured
10:29:58.068 › Google oAuth is configured
[47221:1108/103002.376648:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

**Comment by alchaplinsky** [comment]
Ok, this looks right. It should not prompt with an error and should not prevent user from using the app.

**Comment by Phil353556** [comment]
Absolutely ... Many thanks @alchaplinsky  for the work done. Phil
