### ISSUE TITLE
Fatal error at set up

### ISSUE THREAD

**Issue by Nasnl** [swiftyapp/swifty#11]
I got stuck right at the set up. Hope it helps to share this...

```
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at d.setBounds (C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\electron.asar\browser\api\browser-window.js:16:25)
    at d.resize (C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:335:5211)
    at d.enlarge (C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:335:6205)
    at appId.authSuccess (C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:335:16343)
    at C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:335:16269
    at EventEmitter.<anonymous> (C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:335:13711)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (C:\Users\Jeroen\AppData\Local\Programs\Swifty\resources\electron.asar\browser\api\web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
```

---

Swifty 0.3.0-beta.1
Electron 6.0.9
win32 10.0.18362
Locale: en-US

**Comment by alchaplinsky** [comment]
@Nasnl Sure, thanks for the report!

**Comment by alchaplinsky** [comment]
Hey @Nasnl could you check [v0.3.2-beta.2](https://github.com/swiftyapp/swifty/releases/tag/v0.3.0-beta.2)? This issue should've been fixed there.
