### ISSUE TITLE
Why is it like this？

### ISSUE THREAD

**Issue by MuffinMan1874** [swiftyapp/swifty#130]
```
TypeError: this.window[t.message] is not a function
    at window:message (C:\Users\吟游诗人\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:2:7967168)
    at IpcMainImpl.<anonymous> (C:\Users\吟游诗人\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:2:7970843)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
```

---

Swifty 0.6.10
Electron 21.2.2
win32 10.0.19044
Locale: zh-CN

**Comment by alchaplinsky** [comment]
This should be fixed in [v0.6.11](https://github.com/swiftyapp/swifty/releases/tag/v0.6.11)

**Comment by MuffinMan1874** [comment]
Why is the bug fixed so fast ？

**Comment by alchaplinsky** [comment]
Well, sorry. Next time I'll wait for a couple of days 😄
