### ISSUE TITLE
Cannot connect to Google Drive on Kubuntu after installing deb through Terminal

### ISSUE THREAD

**Issue by ktspeedruns** [swiftyapp/swifty#141]
```
Error: Sync is not configured
    at Sr.perform (/opt/Swifty/resources/app.asar/main/index.js:2:7981816)
    at vault:sync:connect (/opt/Swifty/resources/app.asar/main/index.js:2:7985797)
    at IpcMainImpl.<anonymous> (/opt/Swifty/resources/app.asar/main/index.js:2:7989255)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80718)
    at EventEmitter.emit (node:events:513:28)
```

---

Swifty 0.6.11
Electron 22.0.0
linux 5.19.0-31-generic
Locale: en-US

**Comment by alchaplinsky** [comment]
Thanks for the report.

In Swifty 0.6.7 through 0.6.13 the **Connect Google Drive** button in Settings skips the Google sign-in step entirely and jumps straight to syncing. Since there are no Google credentials stored yet, it fails immediately with "Sync is not configured". It has been broken since late 2022 and there is no setting or workaround that makes it work in these versions.

There will not be a fix for the old app. Swifty is no longer maintained. It has been rewritten from scratch and lives on as **Rowel**, which is what this repository contains today. Rowel supports Google Drive sync, using your own Google OAuth client so no credentials are bundled with the app. The setup steps are in the README under "Google Drive sync".

Closing this as it will not be fixed in Swifty.
