### ISSUE TITLE
Bug with Synchronizing vault with Google Drive

### ISSUE THREAD

**Issue by Philip9001** [swiftyapp/swifty#158]
**Describe the bug**
unable to Synchronize the vault with Google Drive

**To Reproduce**
1.  Open Swifty and click on Vault Settings Icon
2. Click on "Connect your Google Drive" button under the title "Synchronize" 
3. pop up shows with the title "Unhandled Promise Rejection"

```
Unhandled Promise Rejection

Error: Sync is not configured
    at Sr.perform (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8103263)
    at vault:sync:connect (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8107235)
    at IpcMainImpl.<anonymous> (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8110701)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80713)
    at EventEmitter.emit (node:events:513:28)
```

**Expected behavior**
Authentication and Synchronization of vault with Google Drive.

**Screenshots**
<img width="895" alt="Screenshot 2023-05-07 at 10 42 01 AM" src="https://user-images.githubusercontent.com/90056233/236684380-a9673ec0-3839-4f5e-94d7-9949e7bb1bc2.png">

**Desktop and Version:**
 - OS: MacOS
 - Swifty 0.6.13
 - Electron 23.0.0
 - darwin 22.4.0
 - Locale: en-US

**Additional context**
Installed on MacOS with 
```
brew install --cask swifty
```

**Comment by alchaplinsky** [comment]
Thanks for the report.

In Swifty 0.6.7 through 0.6.13 the **Connect Google Drive** button in Settings skips the Google sign-in step entirely and jumps straight to syncing. Since there are no Google credentials stored yet, it fails immediately with "Sync is not configured". It has been broken since late 2022 and there is no setting or workaround that makes it work in these versions.

There will not be a fix for the old app. Swifty is no longer maintained. It has been rewritten from scratch and lives on as **Rowel**, which is what this repository contains today. Rowel supports Google Drive sync, using your own Google OAuth client so no credentials are bundled with the app. The setup steps are in the README under "Google Drive sync".

Closing this as it will not be fixed in Swifty.
