### ISSUE TITLE
Google Drive Sync issue while the connection

### ISSUE THREAD

**Issue by chadiso** [swiftyapp/swifty#186]
**Describe the bug**
Hey, getting this error while Syncing with Google Drive, on a fresh Mac OS Sonoma set up:
`Unhandled Promise Rejection
Error: Sync is not configured
    at Sr.perform (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8103263)
    at vault:sync:connect (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8107235)
    at IpcMainImpl.<anonymous> (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8110701)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80713)
    at EventEmitter.emit (node:events:513:28)`

**To Reproduce**
1. Download new build, install Swifty
2. Login, goto Settings
3. Hit Synchronize / Connect your Google Drive
4. Get the above error

**Expected behavior**
Can smoothly set up Google Drive sync feature

**Screenshots**
<img width="937" alt="image" src="https://github.com/swiftyapp/swifty/assets/6837253/9acbfb4b-70de-4c7e-aad7-bacecfdb6c4c">

**Desktop (please complete the following information):**
 - MacOS Sonoma
 - Version 14.1.2 (23B92)

**Additional context**
I have everything well set up on my 2nd machine, so actually wanted to migrate Swifty and use it on the new one

Thanks in advance! You're doing a great tool! I'm using it on my daily basis, love it! 🙌

**Comment by chadiso** [comment]
Hey, any change to fix this? I can't synchronize with my laptops :(

**Comment by alchaplinsky** [comment]
Hey @chadiso,
This seems like an issue with GDrive credentials file that Swifty stores on your machine. Could you try deleting it by 
`rm  ~/Library/Application\ Support/Swifty/auth/gdrive.swftx` 

and re-connect google drive in settings?

**Comment by chadiso** [comment]
Thanks for the response, @alchaplinsky!
I did try, deleted that file, and restarted Swifty. However, it pops the same error:
`
Unhandled Promise Rejection
Error: Sync is not configured
    at Sr.perform (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8103263)
    at vault:sync:connect (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8107235)
    at IpcMainImpl.<anonymous> (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8110701)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80713)
    at EventEmitter.emit (node:events:513:28)
`

**Comment by Suhas1104** [comment]
I did fix this and raised a PR for this issue @alchaplinsky @chadiso, basically it wouldnt authenticate on clicking connect to google drive and it would throw this error.

**Comment by chadiso** [comment]
@Suhas1104 Wow, that's just great! @alchaplinsky Could you please have a look? Thanks! 🙌

**Comment by alchaplinsky** [comment]
Swifty is no longer maintained. It has been rewritten from scratch and lives on as **Rowel**, which is what this repository contains today. Rowel supports Google Drive sync, using your own Google OAuth client so no credentials are bundled with the app. The setup steps are in the README under "Google Drive sync".
