### ISSUE TITLE
Getting this error when i click Connect your Google Drive in Synchronize

### ISSUE THREAD

**Issue by uncommonthinker** [swiftyapp/swifty#188]
```
Error: Sync is not configured
    at Sr.perform (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8103263)
    at vault:sync:connect (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8107235)
    at IpcMainImpl.<anonymous> (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:2:8110701)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80713)
    at EventEmitter.emit (node:events:513:28)
```

---

Swifty 0.6.13
Electron 23.0.0
darwin 23.1.0
Locale: en-GB

**Comment by uncommonthinker** [comment]
Already a bug was raised and assigned.
https://github.com/swiftyapp/swifty/issues/186

Closing this.
