### ISSUE TITLE
On sync Error: No refresh token is set

### ISSUE THREAD

**Issue by alchaplinsky** [swiftyapp/swifty#21]
```
Error: No refresh token is set.
    at u.refreshTokenNoCache (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:84061)
    at u.refreshToken (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:83743)
    at u.getRequestMetadataAsync (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:86109)
    at u.requestAsync (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:87230)
    at u.request (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:87099)
    at l (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:203840)
    at Object.t.createAPIRequest (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:203935)
    at c.list (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:11:2649581)
    at O.exists (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:353:7948)
    at O.folderExists (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:353:7513)
```

---

Swifty 0.4.4
Electron 8.1.1
darwin 19.3.0
Locale: en-GB

**Comment by alchaplinsky** [comment]
A temporary fix: Re-connect Google Drive in Settings

**Comment by alchaplinsky** [comment]
It's been a while since this error showed up, so it looks like it was fixed in the refactoring
