### ISSUE TITLE
Error "Unhandled Promisse"

### ISSUE THREAD

**Issue by jjsquady** [swiftyapp/swifty#28]
```
Error: Request timed out
    at Timeout.o [as _onTimeout] (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:11:83486)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

---

Swifty 0.4.6
Electron 8.2.3
darwin 19.3.0
Locale: en-US

**Comment by alchaplinsky** [comment]
This should be fixed in v0.6.0
