### ISSUE TITLE
Keep getting this error upon start-up

### ISSUE THREAD

**Issue by PoseidonsCave** [swiftyapp/swifty#38]
```
Error: New version 0.5.2 is not signed by the application owner: publisherNames: Developer ID Application: Oleksandr Chaplinsky (UFBL3F444A), raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Michael\\AppData\\Local\\swifty-updater\\pending\\temp-Swifty-Setup-0.5.2.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at t.newError (C:\Users\Michael\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:1:30613)
    at Object.task (C:\Users\Michael\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:10:117287)
    at async g.executeDownload (C:\Users\Michael\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:1:286322)
```

---

Swifty 0.5.1
Electron 9.0.0
win32 10.0.18362
Locale: en-US

**Comment by alchaplinsky** [comment]
Looks like Windows-specific issue

**Comment by alchaplinsky** [comment]
@PoseidonsCave Try version 0.5.3, should be fixed there.
