### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by emo44** [swiftyapp/swifty#42]
```
Error: New version 0.6.0 is not signed by the application owner: publisherNames: Developer ID Application: Oleksandr Chaplinsky (UFBL3F444A), raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "El archivo \temp-Swifty-Setup-0.6.0.exe no está firmado digitalmente. No se puede ejecutar este script en el sistema actual. Para obtener más información acerca de la ejecución de scripts y la configuración de la directiva de ejecución, consulta about_Execution_Policies en https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at t.newError (C:\Users\emo\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:1:30810)
    at Object.task (C:\Users\emo\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:10:114724)
    at async g.executeDownload (C:\Users\emo\AppData\Local\Programs\Swifty\resources\app.asar\main\index.js:1:287171)
```

---

Swifty 0.5.4
Electron 9.2.1
win32 10.0.18363
Locale: es

**Comment by alchaplinsky** [comment]
Try installing the latest version 0.6.0
