### ISSUE TITLE
Potential update error on startup

### ISSUE THREAD

**Issue by jerdeb** [swiftyapp/swifty#49]
```
Error: ZIP file not provided: [
  {
    "url": "https://github.com/alchaplinsky/swifty/releases/download/v0.6.2/Swifty-0.6.2.dmg",
    "info": {
      "url": "Swifty-0.6.2.dmg",
      "sha512": "karru8TlSjFNp1KHo6ZeG+2Sg+NhCBNpV+mPZ3ZMmpkL/3Sdh4boEA8/pXauU4dfxAekYuw5aKrihtJmBraZ8g==",
      "size": 79586130
    }
  }
]
    at t.newError (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:30811)
    at p.doDownloadUpdate (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:10:111020)
    at p.downloadUpdate (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:284202)
    at p.doCheckForUpdates (/Applications/Swifty.app/Contents/Resources/app.asar/main/index.js:1:283552)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

---

Swifty 0.6.1
Electron 10.1.3
darwin 19.6.0
Locale: en-GB

**Comment by alchaplinsky** [comment]
Hey @jerdeb, thanks for pointing out! This has been fixed.
