### ISSUE TITLE
Firefox error

### ISSUE THREAD

**Issue by gitSaptarshi** [swiftyapp/swifty#51]
```
Error: Swifty folder was not found on GDrive
    at U.readRemoteVault (/opt/Swifty/resources/app.asar/main/index.js:616:132480)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

---

Swifty 0.6.2
Electron 10.1.5
linux 5.9.16-200.fc33.x86_64
Locale: en-GB

**Comment by alchaplinsky** [comment]
@gitSaptarshi Hey, how did you manage to get this error? Did you use Swifty before and then just deleted it's folder in GDrive?

**Comment by gitSaptarshi** [comment]
No, I installed Swifty for the first time. Then tried to add GDrive. There is no folder called Swiftly in my GDrive already.

**Comment by alchaplinsky** [comment]
@gitSaptarshi Well Swifty should create one if it does not exist on your drive. Are you able to get the same error if you restart the application and try connecting GDrive again?

**Comment by gitSaptarshi** [comment]
> @gitSaptarshi Well Swifty should create one if it does not exist on your drive. Are you able to get the same error if you restart the application and try connecting GDrive again?

Yes, this error persists. I reconnected my GDrive to the app but after restarting, the connection was lost and had to be reconnected again.
