### ISSUE TITLE
Error message during use (checking for updates)

### ISSUE THREAD

**Issue by tim-vandenbosch** [swiftyapp/swifty#58]
**Describe the bug**
While using the application, it tries to check for updates but fails

**To Reproduce**
1. Open application/give master password
2. Wait

**Expected behavior**
Checking successfully for updates

**Screenshots**
![image](https://user-images.githubusercontent.com/10880963/105627025-5efecf80-5e34-11eb-8267-8228ff986a6f.png)
Full Error message:
Unhandled Promise Rejection
Error: New version 0.6.3 is not signed by the application owner: publisherNames: Developer ID Application: Oleksandr Chaplinsky (UFBL3F444A), raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C://Users//PcAdmin//AppData//Local//swifty-updater//pending//temp-Swifty-Setup-0.6.3.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at t.newError (C:/Users/PcAdmin/AppData/Local/Programs/Swifty/resources/app.asar/main/index.js:1:30811)
    at Object.task (C:/Users/PcAdmin/AppData/Local/Programs/Swifty/resources/app.asar/main/index.js:10:114594)
    at async g.executeDownload (C:/Users/PcAdmin/AppData/Local/Programs/Swifty/resources/app.asar/main/index.js:1:287172)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro V.1909 B.18363.1316

**Comment by alchaplinsky** [comment]
@tim-vandenbosch Could you try [v0.6.4](https://github.com/swiftyapp/swifty/releases/tag/v0.6.4)? The issue should no longer be present.
